SOURCES := pools.c dynstring.c dynarr.c main.c scanner.c parser.c interpreter.c vm.c
HEADERS := pools.h dynstring.h dynarr.h compiler.h

	gcc -Wall -O0 -g -o simplang $(SOURCES)
simplang : $(SOURCES) $(HEADERS) Makefile
