SOURCES := pools.c dynstring.c dynarr.c main.c scanner.c parser.c interpreter.c
HEADERS := pools.h dynstring.h dynarr.h compiler.h

simplang : $(SOURCES) $(HEADERS)
	gcc -Wall -O0 -g -o simplang $(SOURCES)
