let main jfhvjfhfhgiusfdguhsdfguiieufgudifgniudfguibdsfgjsdfiugeiugneiounuefnguoenguoehguoehroughuoeghrouiehrguherguheguioherguherguheguioerhguerhguehrguheurgoiheurgiohueiorghuioerhgueohgruehrguoherguioherugiohreouigheorugherouhguoreihgueiohgehrgoiuehrguheroiughreuoghiouerhguorehguoherogheougheouhgeorghoerhgouerhgouerhgoerhgoehgeoherogheoghoehrgoergoherogeorghoergoegoergoerge =
  123
end
